[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "../targets/x86_64-unknown-none.json"

[target.i686-unknown-none]
rustflags = ["-C", "link-arg=-Tlinker.ld"]
