[package]
name = "kernel"
version = "0.1.0"
authors = ["Collin <chbaker0@gmail.com>"]
edition = "2021"

[features]
default = ["rust-bootloader"]
rust-bootloader = ["dep:bootloader"]

[workspace]
members = [
    ".",
    "buildutil",
    "loader",
    "mkimage",
    "shared",
]
default-members = ["."]
resolver = "2"

[dependencies]
bootloader = { version = "0.10.12", optional = true }
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
log = "0.4.14"
once_cell = { version = "1.9.0", default-features = false }
shared = { path = "shared" }
spin = "0.9.2"

[build-dependencies]
anyhow = "1.0"
buildutil = { path = "buildutil" }

[target.x86_64-unknown-none.dependencies]
x86_64 = "0.14.7"
