[package]
name = "kernel"
version = "0.1.0"
authors = ["Collin <chbaker0@gmail.com>"]
edition = "2021"

[workspace]
members = [
    ".",
    "buildutil",
    "mkimage",
    "shared",
]
default-members = ["."]
resolver = "2"

[dependencies]
bitflags = "1.3"
lazy_static = {version = "1.4.0", features = ["spin_no_std"]}
log = "0.4.14"
multiboot2 = "0.14.1"
once_cell = { version = "1.17.1", default-features = false }
shared = { path = "shared", default-features = false }
spin = "0.9.5"
static_assertions = "1.1.0"

[dependencies.intrusive-collections] 
version = "0.9.5"
default-features = false
features = ["nightly"]

[build-dependencies]
anyhow = "1.0"
buildutil = { path = "buildutil" }
multiboot2-header = "0.2.0"

[target.x86_64-unknown-none.dependencies]
x86_64 = "0.14.10"
