[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.default]
alias = "image"

[tasks.image]
command = "mkdir -p out/efi/boot && cp target/x86_64-unknown-uefi/debug/loader.efi out/efi/boot/bootx64.efi"
dependencies = ["loader"]

[tasks.loader]
command = "cargo"
args = ["build", "-p", "loader", "--target", "x86_64-unknown-uefi"]
