[package]
name = "kernel"
version = "0.0.1"
authors = ["chbaker0@gmail.com"]
build = "build.rs"

[lib]
name = "kernel"
path = "src/lib.rs"
crate-type = ["staticlib"]

[dependencies]
rlibc = "^1"
shared = { path = "../shared" }