[package]
name = "kernel"
version = "0.0.1"
authors = ["chbaker0@gmail.com"]
build = "build.rs"

[lib]
name = "kernel"
path = "src/lib.rs"
crate-type = ["staticlib"]

[dependencies]
x86_64 = "0.2.11"
intrusive-collections = { version = "0.7", features = ["nightly"] }
log = "0.4.5"
shared = { path = "../shared" }
spin = "0.4.9"

[dependencies.compiler_builtins]
git = "https://github.com/rust-lang-nursery/compiler-builtins"
features = ["c", "no-lang-items"]

[dependencies.lazy_static]
version = "1.1.0"
features = ["spin_no_std"]
