[target.i686-unknown-none]
rustflags = ["-C", "link-arg=-Tloader/src/linker.ld"]

[target.x86_64-unknown-none]
rustflags = ["-C", "link-arg=-Tsrc/linker.ld"]
runner = "cargo run --package mkimage --"

[alias]
kbuild = "build --target targets/x86_64-unknown-none.json -Zbuild-std=core,compiler_builtins -Zbuild-std-features=compiler-builtins-mem"
kimage = "run --target targets/x86_64-unknown-none.json -Zbuild-std=core,compiler_builtins -Zbuild-std-features=compiler-builtins-mem"
