[env]
# Ideally we wouldn't disable stacked borrow checking, but unfortunately some
# intrusive collection code isn't compatible with the rules.
MIRIFLAGS = "-Zmiri-strict-provenance -Zmiri-disable-stacked-borrows"

[target.x86_64-unknown-none]
rustflags = ["-C", "link-arg=-Tsrc/linker.ld"]
runner = "cargo run --package mkimage --"

[alias]
kbuild = "build --target targets/x86_64-unknown-none.json -Zbuild-std=core,alloc,compiler_builtins -Zbuild-std-features=compiler-builtins-mem"
ibuild = "build --package init --target targets/x86_64-unknown-testos.json -Zbuild-std=core,compiler_builtins -Zbuild-std-features=compiler-builtins-mem"
kimage = "run --target targets/x86_64-unknown-none.json -Zbuild-std=core,alloc,compiler_builtins -Zbuild-std-features=compiler-builtins-mem"
kcheck = "check --target targets/x86_64-unknown-none.json -Zbuild-std=core,alloc,compiler_builtins -Zbuild-std-features=compiler-builtins-mem"
kfix = "fix --target targets/x86_64-unknown-none.json -Zbuild-std=core,alloc,compiler_builtins -Zbuild-std-features=compiler-builtins-mem"
scheck = "check --package shared"
icheck = "check --package init --target targets/x86_64-unknown-testos.json -Zbuild-std=core,compiler_builtins -Zbuild-std-features=compiler-builtins-mem"
kclippy = "clippy --target targets/x86_64-unknown-none.json -Zbuild-std=core,compiler_builtins -Zbuild-std-features=compiler-builtins-mem"
sclippy = "clippy --package shared"
iclippy = "clippy --package init --target targets/x86_64-unknown-testos.json -Zbuild-std=core,compiler_builtins -Zbuild-std-features=compiler-builtins-mem"
stest = "test --package shared"
kdoc = "doc --target targets/x86_64-unknown-none.json --document-private-items -Zbuild-std=core,compiler_builtins -Zbuild-std-features=compiler-builtins-mem"
sdoc = "doc --package shared --document-private-items"
idoc = "doc --document-private-items --package init --target targets/x86_64-unknown-testos.json -Zbuild-std=core,compiler_builtins -Zbuild-std-features=compiler-builtins-mem"
