[target.i686-unknown-none]
rustflags = ["-C", "link-arg=-Tloader/src/linker.ld"]

[target.x86_64-unknown-none]
rustflags = ["-C", "link-arg=-Tsrc/linker.ld"]
runner = "cargo run --package mkimage --"

[alias]
kbuild = "build --target targets/x86_64-unknown-none.json -Zbuild-std=core,compiler_builtins -Zbuild-std-features=compiler-builtins-mem"
kimage = "run --target targets/x86_64-unknown-none.json -Zbuild-std=core,compiler_builtins -Zbuild-std-features=compiler-builtins-mem"
kcheck = "check --target targets/x86_64-unknown-none.json -Zbuild-std=core,compiler_builtins -Zbuild-std-features=compiler-builtins-mem"
lcheck = "check --package loader --target targets/i686-unknown-none.json -Zbuild-std=core,compiler_builtins -Zbuild-std-features=compiler-builtins-mem"
scheck = "check --package shared"
kclippy = "clippy --target targets/x86_64-unknown-none.json -Zbuild-std=core,compiler_builtins -Zbuild-std-features=compiler-builtins-mem"
lclippy = "clippy --package loader --target targets/i686-unknown-none.json -Zbuild-std=core,compiler_builtins -Zbuild-std-features=compiler-builtins-mem"
sclippy = "clippy --package shared"
stest = "test --package shared"
kdoc = "doc --target targets/x86_64-unknown-none.json --document-private-items -Zbuild-std=core,compiler_builtins -Zbuild-std-features=compiler-builtins-mem"
ldoc = "doc --package loader --target targets/i686-unknown-none.json --document-private-items -Zbuild-std=core,compiler_builtins -Zbuild-std-features=compiler-builtins-mem"
sdoc = "doc --package shared --document-private-items"
