[package]
name = "loader"
version = "0.0.1"
authors = ["chbaker0@gmail.com"]

[lib]
name = "loader"
path = "src/lib.rs"
crate-type = ["staticlib"]

[dependencies]
shared = { path = "../shared" }

[dependencies.compiler_builtins]
git = "https://github.com/rust-lang-nursery/compiler-builtins"
features = ["c", "no-lang-items"]
