[package]
name = "shared"
version = "0.1.0"
authors = ["Collin <chbaker0@gmail.com>"]
edition = "2018"

[dependencies]
itertools = { version = "0.9.0", default-features = false }

[dependencies.arrayvec]
version = "0.5.1"
default-features = false
features = ["array-sizes-33-128"]
