[package]
name = "shared"
version = "0.1.0"
authors = ["Collin <chbaker0@gmail.com>"]
edition = "2018"

[dependencies]
itertools = { version = "0.9.0", default-features = false }
log = "0.4.11"
spin = "0.9.2"
static_assertions = "1.1.0"

[dependencies.arrayvec]
version = "0.5.2"
default-features = false
features = ["array-sizes-33-128"]

[dev-dependencies]
quickcheck = "~0.9"
quickcheck_macros = "~0.9"
