[package]
name = "buildutil"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { workspace = true, features = ["derive"] }
eyre = { workspace = true }
multiboot2-header = { workspace = true }
