[package]
name = "buildutil"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true, features = ["derive"] }
multiboot2-header = { workspace = true }
