[package]
name = "mkimage"
version = "0.1.0"
edition = "2021"

[features]
default = ["rust-bootloader"]
rust-bootloader = ["dep:bootloader-locator"]

[dependencies]
anyhow = "1.0"
bootloader-locator = { version = "0.0.4", optional = true }
buildutil = { path = "../buildutil" }
cargo_metadata = "0.14.2"
clap = { version = "3.1", features = ["derive"] }
