[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "../targets/i686-unknown-none.json"

[target.i686-unknown-none]
rustflags = ["-C", "link-arg=-Tsrc/linker.ld"]
